version: '3.9'

services:
  db:
    image: postgres:16
    container_name: shreddit_db
    environment:
      POSTGRES_DB: shreddit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d shreddit"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: .
    container_name: shreddit_backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shreddit
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  ui:
    image: nginx:1.27
    container_name: shreddit_ui
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ../frontend/build:/usr/share/nginx/html:ro
      - ../frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  pgdata:
